# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  ubuntu2204:
    machine:
      image: ubuntu-2204:2022.10.2 
  alpine317:
    docker:
      - image: docker.io/alpine:3.17
  opensuse15:
    docker:
      - image: docker.io/opensuse/leap:15
  archlinux:
    docker:
      - image: docker.io/archlinux:latest
  debian11:
    docker:
      - image: docker.io/debian:11
  debian12:
    docker:
      - image: docker.io/debian:12
  fedora37:
    docker:
      - image: docker.io/fedora:37
  fedora38:
    docker:
      - image: docker.io/fedora:38
  centos9:
    docker:
      - image: quay.io/centos/centos:stream9

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  linux:
    parameters:
      distro:
        type: executor
    executor: << parameters.distro >>
    steps:
      - run:
          name: Install build tools
          command: |
            dnf -y install autoconf automake gcc git iproute libtool make nmap-ncat pkg-config procps sudo || true
            dnf -y install libtirpc-devel || true
            dnf -y install make || true
            apt update || true
            apt install -y autoconf automake gcc git groff iproute2 libtirpc-dev libtool make ncat pkg-config procps sudo || true
            pacman -Sy --noconfirm autoconf automake gcc git groff iproute2 libtool make pkg-config procps sudo || true
            zypper install -y autoconf automake gcc git groff gzip iproute2 libtool make pkg-config procps sudo tar make || true
            apk add sudo autoconf automake bash gcc git groff gzip iproute2 libtool linux-headers make musl-dev nmap-ncat pkgconf strace which || true
      - when:
          condition:
            equal: [ fedora38, << parameters.distro >> ]
          steps:
            - run:
                command: |
                  dnf -y install lcov gem procps python3-pip
                  pip3 install --user cpp-coveralls
      - checkout
      - run:
          name: Configure
          command: |
            ./Configure -n linux
      - when:
          condition:
            equal: [ fedora38, << parameters.distro >> ]
          steps:
            - run:
                name: Build
                command: |
                  CC="cc"
                  CC_EXTRA="--coverage"
                  make -j 2 CDEF="${CC_EXTRA}" CC="${CC} ${CC_EXTRA}"
      - when:
          condition:
            not:
              equal: [ fedora38, << parameters.distro >> ]
          steps:
            - run:
                name: Build
                command: |
                  make -j 2
      - run:
          name: Test
          command: |
            bash ./check.bash linux
      - when:
          condition:
            equal: [ fedora38, << parameters.distro >> ]
          steps:
            - run:
                name: Report coverage
                command: |
                  lcov -c -b . -d . -o coverage.info
                  /root/.local/bin/coveralls --root .
      - run:
          name: Build and test using autotools
          command: |
            git clean -fdx .
            autoreconf -vif
            ./configure
            make
            sudo make install
            make check
            cat test-suite.log
            make distcheck
  nixos:
    docker:
      - image: docker.io/nixos/nix:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            nix-channel --update
            nix-build
  monterey:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: Install pkg-config
          command: |
            brew install pkg-config libtool autoconf automake
      - run:
          name: Configure
          command: |
            LSOF_INCLUDE=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include ./Configure -n darwin
      - run:
          name: Build
          command: |
            make -j 2
      - run:
          name: Test
          command: |
            bash ./check.bash darwin
      - run:
          name: Build using autotools
          command: |
            git clean -fdx .
            autoreconf -vif
            ./configure
            make
            DESTDIR=$PWD/prefix make install
            make check
      - run:
          name: Rebuild and test using distribution tarball
          command: |
            make dist
            mkdir temp
            cd temp
            tar xvf ../lsof-*.tar.gz
            cd lsof-*
            ./configure
            make
            DESTDIR=$PWD/prefix make install
            make check

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  gnulinux-workflow:
    jobs:
      - linux:
          matrix:
            parameters:
              distro: [fedora37, fedora38, centos9, debian11, debian12, ubuntu2204, archlinux, opensuse15, alpine317]
      - nixos
      - monterey
